on:
  release:
    types: [created]

jobs:
  build:
    name: Release Go Binary
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - run: sudo bash ./deploy.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/ott-play-epg-converter_linux_amd64.bin.gz
            build/ott-play-epg-converter_linux_arm64.bin.gz
            build/ott-play-epg-converter_windows_386.exe.gz
            build/ott-play-epg-converter_windows_amd64.exe.gz
